# Generated by Django 4.1.3 on 2023-03-24 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_category_alter_course_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='Category',
            new_name='category',
        ),
    ]
