# Generated by Django 4.1.3 on 2023-05-03 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_course_ishome_alter_course_isactive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='imageUrl',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
    ]
