# Generated by Django 4.1.3 on 2023-05-09 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_slider'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slider',
            old_name='is_acrive',
            new_name='is_active',
        ),
    ]
